Fix some issues with number inputs
AlexPoirier1/react-controlled-inputs pull request #2
Opened 2017-11-22 21:59 UTC by JsGarneau

- Fix la gestion de la virgule
- Fix le parseFloat qui parse un nombre invalid plutôt que renvoyer NaN

2017-11-28 20:32 UTC, AlexPoirier1 requested changes

2017-11-28 20:32 UTC, AlexPoirier1 commented on src/components/number-input.js
> +        e.target.value = e.target.value.replace(',', '.');
Les tests fail sur ceci.
```
1 failing

  1) Inputs :: Given any Input when typing, should call the onChange passed as props:
     TypeError: e.target.value.replace is not a function
      at CurrencyInput.onChange (src/components/number-input.js:31:41)
      at Context.<anonymous> (tests/components/input-test.js:70:13)
```

2017-11-28 20:32 UTC, AlexPoirier1 commented on src/utils/formatter.js
> +    _frenchReplace = value => _.trim(value.replace('-', '').replace(',', '\u00A0').replace('.', ','), ',.');
Ça fait quoi ça? C'est pour quel use case?

2017-11-29 15:14 UTC, JsGarneau commented on src/components/number-input.js
> +        e.target.value = _.isString(e.target.value) ? e.target.value.replace(',', '.') : e.target.value;
Ca fix le test, mais vu que c'est pas vraiment un input de type `number` ca me surprendrait qu'on reçoive autre chose qu'une numeric string, non?

2017-11-29 17:07 UTC, JsGarneau commented on src/utils/formatter.js
> +    _frenchReplace = value => _.trim(value.replace('-', '').replace(',', '\u00A0').replace('.', ','), ',.');
Dafuk, mon comment à disparu. En gros, quand on à un trailing `,` ou `.` il est affiché même après formatage -> `500, $`, ca le retire à l'affichage.

2017-12-01 20:53 UTC, AlexPoirier1 commented
@JsGarneau On s'en jasera, je suis pas d'accord avec les changements dans le number-input mais je comprend mal pourquoi on doit le changer anyway ( la partie `Fix le parseFloat qui parse un nombre invalid plutôt que renvoyer NaN`)

2017-12-01 20:57 UTC, AlexPoirier1 commented on src/utils/formatter.js
> +    _frenchReplace = value => _.trim(value.replace('-', '').replace(',', '\u00A0').replace('.', ','), ',.');
Je préfèrerais qu'on ne retire pas magiquement de caractère de l'input. Ce serait un bon moment pour ajouter les validations (qui empêchent l'envois d'une valeur invalide et affichent l'input en rouge)

2017-12-04 17:02 UTC, AlexPoirier1 approved these changes

2017-12-04 17:02 UTC, merged